filebeat.inputs:
  - type: log
    paths: [ "/usr/share/filebeat/logs/exception.log" ]
    tags:  [ "exception_log" ]
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  - type: log
    paths: [ "/usr/share/filebeat/logs/warn.log" ]
    tags:  [ "warn_log" ]
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

  - type: log
    paths: [ "/usr/share/filebeat/logs/error.log" ]
    tags:  [ "error_log" ]
    multiline.pattern: '^\d{4}-\d{2}-\d{2}'
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]